### ISSUE TITLE
error in calcul amount_untaxed

### ISSUE THREAD

**Issue by lammh** [adhoc-dev/odoo-addons#237]
Hello,
I add 2 products with 10% global discount, but sum of amount_untaxed is not correct!
![image](https://cloud.githubusercontent.com/assets/7395544/11397859/d581de6e-937c-11e5-8bd7-bf8bef5f4aaa.png)

**Comment by jjscarafia** [comment]
It should not be an error related to the discount module because it only add the discount value on discount column of lines.
I thin that amount untaxed is related to the tax 18 configuration or another module breaking something.
I close the issue, re-open it if you think it is still and error and you have more information.
