### ISSUE TITLE
portal_project_issue_mods - unable to install on v8

### ISSUE THREAD

**Issue by ghost** [adhoc-dev/odoo-addons#62]
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `state` does not exist

project_issue_solutions is installed.

**Comment by jjscarafia** [comment]
Hi Ray, we have make it "Installable: False" because we are not using it no more. 
Now our costumers upload issues from their own odoo instance and then have default issues access on our database (only read access). 
The modules related to this new functionalities are in https://github.com/ingadhoc/odoo-support
Thanks
Juan
