### ISSUE TITLE
interested in moving product_dimensions to OCA/product-atribute?

### ISSUE THREAD

**Issue by lepistone** [adhoc-dev/odoo-addons#90]
Hi!

I was wondering if you would agree with including the `product_dimensions` module into the OCA repository `product-attribute`.

If you agree, I can do that with a git extraction (thus, preserving your full authorship and history). This would require the signature of the OCA Contributor Licence Agreement by the two committers of that module: @jjscarafia @nicomacr.

In any case, thanks a lot for your work!

Leonardo

**Comment by jjscarafia** [comment]
Yes please! It would be great. We both have signed the OCA CLA.
Let me know if you need anything else. 
Let me know when done so that I can delete module from this repo. 
I would like to make PR to include our modules that can be intereset for OCA, if you have any tutorial that could help (I can do that with a git extraction (thus, preserving your full authorship and history))
Thanks!

**Comment by lepistone** [comment]
@jjscarafia there you are: OCA/product-attribute#89

For the git procedure see for example https://github.com/odoomrp/odoomrp-wip/wiki/Migration-to-OCA

Thanks!
